"""empty message

Revision ID: 0bf2391a921d
Revises: 91c22e93edd7
Create Date: 2017-06-17 14:58:04.986219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf2391a921d'
down_revision = '91c22e93edd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('access_key', sa.String(length=256), nullable=True))
    op.add_column('chat', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_private')
    op.drop_column('chat', 'access_key')
    # ### end Alembic commands ###
