"""empty message

Revision ID: 44b51296980f
Revises: 9e01f73568c2
Create Date: 2017-11-04 23:58:01.543961

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '44b51296980f'
down_revision = '9e01f73568c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'number')
    # ### end Alembic commands ###
