"""empty message

Revision ID: 47b837ea14fa
Revises: 523f8db3a8ac
Create Date: 2017-06-18 08:51:36.170425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b837ea14fa'
down_revision = '523f8db3a8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_create_time')
    # ### end Alembic commands ###
