"""empty message

Revision ID: 523f8db3a8ac
Revises: f922f3febd0c
Create Date: 2017-06-18 08:43:11.411044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523f8db3a8ac'
down_revision = 'f922f3febd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('create_time', sa.Integer(), nullable=True))
    op.drop_column('chat', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chat', 'create_time')
    # ### end Alembic commands ###
