"""empty message

Revision ID: 850ff5f097bc
Revises: e0d83520f2ba
Create Date: 2017-05-20 08:05:46.030119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850ff5f097bc'
down_revision = 'e0d83520f2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('cname', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'cname')
    # ### end Alembic commands ###
