"""empty message

Revision ID: 87339cddaf50
Revises: bf3bd8dfa9e2
Create Date: 2017-06-01 20:45:35.250136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87339cddaf50'
down_revision = 'bf3bd8dfa9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('chat_link', sa.Integer(), nullable=True))
    op.add_column('code', sa.Column('message', sa.String(length=256), nullable=True))
    op.drop_column('code', 'cname')
    op.drop_column('code', 'chat')
    op.add_column('message', sa.Column('chat_link', sa.Integer(), nullable=True))
    op.drop_column('message', 'chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat', sa.INTEGER(), nullable=True))
    op.drop_column('message', 'chat_link')
    op.add_column('code', sa.Column('chat', sa.INTEGER(), nullable=True))
    op.add_column('code', sa.Column('cname', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('code', 'message')
    op.drop_column('code', 'chat_link')
    # ### end Alembic commands ###
