"""empty message

Revision ID: 879a3a97cfb5
Revises: 
Create Date: 2017-03-02 21:42:19.884871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '879a3a97cfb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'author',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('message', 'chat',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('message', 'content',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('message', 'chat',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('message', 'author',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
