"""empty message

Revision ID: 91c22e93edd7
Revises: 90bf669c739d
Create Date: 2017-06-12 19:27:34.837258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c22e93edd7'
down_revision = '90bf669c739d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'content_ru')
    op.drop_column('message', 'content_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('content_ru', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
