"""empty message

Revision ID: 93517dc980fa
Revises: 0bf2391a921d
Create Date: 2017-08-01 12:35:57.458124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93517dc980fa'
down_revision = '0bf2391a921d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
