"""empty message

Revision ID: 9a8308b7223d
Revises: bc0e56b32646
Create Date: 2017-03-29 22:14:19.584373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8308b7223d'
down_revision = 'bc0e56b32646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('type', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'type')
    # ### end Alembic commands ###
