"""empty message

Revision ID: ad507b48b89a
Revises: ba14d2ca8d06
Create Date: 2017-08-26 12:59:37.177260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad507b48b89a'
down_revision = 'ba14d2ca8d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('initialized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'initialized')
    # ### end Alembic commands ###
