"""empty message

Revision ID: bf3bd8dfa9e2
Revises: 850ff5f097bc
Create Date: 2017-05-22 13:38:38.196676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3bd8dfa9e2'
down_revision = '850ff5f097bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content_en', sa.Text(), nullable=True))
    op.add_column('message', sa.Column('content_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'content_ru')
    op.drop_column('message', 'content_en')
    # ### end Alembic commands ###
