"""empty message

Revision ID: bf6d73bfd002
Revises: 47b837ea14fa
Create Date: 2017-06-18 09:00:40.150453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6d73bfd002'
down_revision = '47b837ea14fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('code_create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'code_create_time')
    # ### end Alembic commands ###
