"""empty message

Revision ID: c4f6fee3d0e5
Revises: a14df3755bdc
Create Date: 2017-06-18 11:04:01.463204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f6fee3d0e5'
down_revision = 'a14df3755bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('code_remove_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'code_remove_time')
    # ### end Alembic commands ###
