"""empty message

Revision ID: e0d83520f2ba
Revises: 51d35801a819
Create Date: 2017-05-10 20:51:55.084894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d83520f2ba'
down_revision = '51d35801a819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('code_type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'code_type')
    # ### end Alembic commands ###
